/**
 * tests/scenarios/_all-wizards.spec.js
 *
 * Smoke sweep: analytical + simulated waveforms for every wizard in
 * WIZARD_CATALOG in a single parameterized file. It is the cheapest check
 * that a wizard still runs end-to-end after a code change.
 *
 * Full per-wizard batteries (A/B/D/E/F/G groups including the adviser flows)
 * live in tests/wizards/<key>.spec.js, generated by makeBatterySpec().
 * Adding a new wizard only requires appending one entry to utils/catalog.js
 * and creating a minimal tests/wizards/<key>.spec.js.
 *
 * Tags:
 *   @scenario  — every test here
 *   @heavy     — wizards flagged 'heavy' in the catalog
 *   @smoke     — flagged wizards
 */

import { test } from '../_coverage.js';
import {
  WIZARD_CATALOG,
  collectConsoleErrors,
  expectNoConsoleErrors,
  wizardAnalyticalAndSimulated,
} from '../utils/index.js';
// F/G adviser flows are exercised per-wizard in tests/wizards/<key>.spec.js
// (generated by makeBatterySpec). This file is the cheap smoke sweep only.

for (const wizard of WIZARD_CATALOG) {
  const heavy = wizard.tags.includes('heavy');
  const smoke = wizard.tags.includes('smoke');
  const tagSuffix = ['@scenario', heavy && '@heavy', smoke && '@smoke'].filter(Boolean).join(' ');

  test.describe(`${wizard.key} ${tagSuffix}`, () => {
    test.setTimeout(heavy ? 360_000 : 120_000);

    test(`${wizard.title}: analytical + simulated`, async ({ page }) => {
      const errors = collectConsoleErrors(page);
      await wizardAnalyticalAndSimulated(page, wizard);
      expectNoConsoleErrors(errors);
    });
  });
}
